env:
  es6: true
  node: true
extends:
  - airbnb-base
  # - plugin:jest/all
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
# rules:

